package mx.pagos.admc.enums;

public enum SectionTypeEnum {
	LOADING_PROJECT,
	DOCUMENTATION,
	LOADING_GUARANTEES,
	DICTAMINATION,
	DICTAMINATION_TEMPLATE,
	DICTUM,
	DIGITALIZATION_INSCRIPTION,
	DIGITALIZATION_CONTRACTS,
	DIGITALIZATION_GUARANTEES
}
