export enum MensajesFijosEnum {
    ERROR_SERVIDOR = 'No se pudo completar la operación',
    ERROR_SERVIDOR_CORREO = 'Error al envíar el correo',
    ALERTA_REQUERIDO = 'Falta un campo requerido',
    OPERACION_EXITOSA = 'Operación exitosa',
    BUSQUEDA_EXITOSA = 'Búsqueda exitosa.',
    CONFIRMACION_OPERACION = '¿Está seguro que desea eliminar el registro?',
    BUSQUEDA_SIN_RESULTADOS = 'Sin resultados',
    CORREO_NO_VALIDO = 'El correo ingresado no es válido',
    TELEFONO_NO_VALIDO = 'El número de teléfono ingresado no es válido',
    FECHA_MSJ = 'Fecha ',
    FECHA_INCIO = 'de inicio incorrecta',
    FECHA_FIN = 'fin incorrecta',
    FECHA_VIGENCIA = 'de vigencia incorrecta',
    FOMRATO_RFC_INVALIDO = 'Por favor ingresa un RFC valido.',
    PROVEEDOR_NO_SELECCIONADO = 'Se necesita elegir un proveedor para continuar',
    // tslint:disable-next-line: max-line-length
    ENTIDAD_SIN_REPRESENTANTES = 'La(s) entidad(es)(s) seleccionada(s) no tienen relacionado(s) representante(s) legal(es), favor de darlo de alta en el catálogo de representantes legales',
    ARCHIVO_YA_AGREGADO = 'El archivo ya ha sido agregado, por favor seleccione otro',
    ARCHIVO_AGREGADO = 'Archivo agregado correctamente',
    DOCUMENTO_NO_ENCONTRADO = 'El documento no fue encontrado',
    CONFIRMACION_VOBO = '¿Confirma el VoBo?',
    RFC_NUEVO = 'EL RFC/ID TAX no ha sido ingresado anteriormente. Se creará un nuevo proveedor',
    RECUPERACION_CONTRASENA = 'Su nueva contraseña fue enviada, por favor revise su correo',
    CONFIRMACION_RECUPERACION_CONTRASENA = '¿Confirma la recuperación de su contraseña?',
    CONTRASENA_INVALIDA = 'Contraseña incorrecta',
    NO_COINCIDEN_CONTRASENAS = 'La contraseña no coincide',
    CONTRASENA_DISTINTAS = 'Su nueva contraseña debe ser diferente a la actual',
    FALTA_DOCUMENTO_PROVEEDOR = 'Falta cargar algún documento requerido del proveedor',
    FALTA_ABOGADO = 'Falta agregar abogado',
    FALTA_CLAUSULAS = 'Falta completar las clausulas',
    FALTA_TESTIGO_REPRESENTANTE = 'Falta agregar un Representante Legal y/o Testigo ',
    FALTA_INFORMACON_SOLICITUD = 'Falta completar información requerida de la solicitud. Favor de validar.',
    ENVIAR_BORRADOR = '¿Enviar borrador a usuario?',
    ENVIAR_VOBO_PROVEEDOR = '¿Enviar VoBo de proveedor y áreas involucradas?',
    EMPRESA_SIN_UNIDADES = 'La empresa no tiene unidades relacionadas',

    ARCHIVO_CARGADO = 'Documento cargado correctamente.',
    ELIMINAR_DIGITALIZACION = '¿Deseas eliminar la digitalización?',
    CONFIRMACION_GUARDAR = '¿Esta seguro que desea guardar cambios?',

    ARCHIVO_VACIO = 'Debe de adjuntar un archivo',
    LISTA_ARCHIVOS_VACIA = 'Debe de adjuntar por lo menos un archivo',
    ARCHIVOS_NO_VALIDO = 'No se puede eliminar el archivo',
    CONFIRMACION_AGREGAR_ARCHIVOS = '¿Desea guardar el archivo en el sistema?',
    CONFIRMAR_ENVIO = 'Una vez enviado no se podrá regresar la solicitud, ¿Está seguro de enviar la solicitud?',
    ERROR_DATOS_GRAFICAS = 'Error no se puedo obtener la informacion para generar la grafica',
    ERROR_DATOS_REPORTE = 'Error al obtener los datos para el reporte',
    NO_DATOS_GRAFICAS = 'No hay resultados para mostrar en la grafica.',
    ERROR_EXTENSION_CONTRATO = 'El tipo de archivo no es válido, (solo puede agregar .doc o docx)',
    ERROR_EXTENSION_ANEXOS = 'El tipo de archivo no es válido, (solo puede agregar: Word, PDF, JPG, PNG.)',
    ERROR_FECHA_AÑO_INVALIDA='No hay resultados para ese año',

    DES_NOTI_SOLI_CELEBRADAS = 'Al atender el contrato se dejaran de enviar alertas diarias.\n ¿Está seguro de marcar como atendido? ',
    ACT_NOTI_SOLI_CELEBRADAS = 'Al desatender el contrato se enviaran alertas diarias.\n ¿Está seguro de marcar como no atendido? ',

    CODIGO_ERRONEO = 'Código no rastreado.',
    FOMRATO_RFC_INVALIDO_PROVEEDOR = 'Formato invalido: Favor de ingresar un RFC valido',

    LISTA_DOCUMENTOS_VACIA = 'La Solicitud de contrato permanecerá en el estatus actual hasta que se haya cargado un archivo de digitalización del contrato.',

    COMENTARIO_REQUERIDO = 'Comentario requerido',
    NOMBRE_REQUERIDO = 'Nombre requerido',
    MAYOR_A_CERO = 'Debe ingresar número mayor a cero',
    ORDEN_PG_DUPLICADA = 'Registro duplicado: orden o archivo anexo',

    ALERTS_DELETE = '¿Esta seguro de eliminar la alerta?',

    NOTICE_DELETE = '¿Esta seguro de eliminar?',

    ADD_HOLIDAY = 'No se puede guardar porque ya existe un día inhábil con la misma fecha.',

    DELETE_HOLIDAY = '¿Esta seguro de eliminar el día inhábil?',
    GESTION_PERFILES_REQUERIDO = 'Faltan campos requeridos',
    DELETE_HOLIDAYS_USER = '¿Esta seguro de eliminar el periodo vacacional?',
    VALIDATE_HOLIDAY = 'El periodo vacacional a sido registrado.',
    VALIDATE_DATE_START = 'Falta agregar fecha inicio.',
    VALIDATE_DATE_END = 'Falta agregar fecha fin.',
    VALIDATE_DATE_HOLIDAY = 'Las fechas deben ser mayor al día actual',
    VALIDATE_DATE_END_HOLIDAY = 'Se necesita ingresar una fecha de fin mayor a la fecha de inicio.',
    INFO_VALIDATE_ENTITY = "Tratamiento que se le dará a la entidad en los documentos. Ej. 'El' Banco, 'La' Entidad, etc.",
    INFO_VALIDATE_REPRE_LEGAL = 'Por favor selecciona una entidad.',
    BINNACLE_ALERT = '¿Está seguro de eliminar los registros de la bitácora?',
    NAME_ANEXO = 'El nombre del anexo no es valido.',
    REPRESENTANTE_LEGAL_VALID_POWER = 'Falta agregar el poder a la(s) entidad(es): *',
    REPRESENTANTE_LEGAL_VALID_ENTITIES = 'Falta agregar Entidades.',
    ADMN_CONFIG = '¿Esta seguro de activar las configuraciones de alto riesgo?',
    SESION_TERMINADA = 'La operación ha finalizado',
    CAMPOS_VACIOS_POR_LLENAR = 'Aún hay campos vacíos',
    USUARIO_EXISTENTE = 'Este usuario ya existe actualmente',
    USUARIO_GUARDADO_CORRECTAMENTE = 'Usuario creado correctamente',
    ERROR_AL_DESCARGAR = 'El sistema no pudo encontrar el archivo, comuníquese con el administrador.',
    AGREGAR_BORRADOR = 'Es necesario cargar un borrador.',
    BORRADOR_NO_EXISTE = 'El archivo dejó de existir',
    NO_EXISTE_FOLIO = 'No existe el folio',
    MESSAGE_CANCELL = 'Folio Finalizado o Cancelado',
    CONFIRMACION_FIRMA_CONTRATO = "Confirme que envió por valija el contrato al evaluador",
    SELECCIONA_EVALUADOR = "Favor de seleccionar un evaluador",
    ERROR_CAMPOS_LLENOS = "Favor de limpiar campos anteriores",
    ERROR_SELECCION_AREA = 'Favor de seleccionar una Área',

    // Digital signature
    DS_ERROR = 'Ha ocurrido un error en el servidor',
    DS_ERROR_LOAD_FILE = 'Debe seleccionar un archivo PDF válido',
    DS_ERROR_DUPLICATE_EMAIL_RECIPIENTS = 'Existen firmantes con el mismo correo electrónico',
    DATA_CONFIGURATION = 'Falta configurar los días',
    DS_ERROR_DUPLICATE_RFC_RECIPIENTS = 'Existen firmantes con el mismo RFC',
    DS_ERROR_RECIPIENTS = 'Debe considerar al menos un destinatario',
    DS_ERROR_ONLY_SIGNER = 'Para poder elegir esta opción primero ingrese sus datos en la sección \"Mi información\"',
    DS_ERROR_LOAD_CONTACTS = 'Ah ocurrido un error al obtener los contactos',
    DS_ERROR_INVALID_URL = 'El enlace para firmar el documento no es válido',
    DS_COPY_INVITE_URL = 'URL de invitación copiada al portapapeles',
    DS_RESEND_INVITITATION_EMAIL = 'Correo de invitación reenviado',
    DS_VIEW_DOCUMENT = 'Documento listo para su visualización',
    DS_DOWNLOAD_DOCUMENT = 'Documento descargado exitosamente',
    DS_DELETE_DOCUMENT = 'Documento eliminado exitosamente',
    DS_STATUS_DOCUMENT = 'Estado del documento correctamente',
    DS_ERROR_NOT_NEEDS_TO_SIGN_PRESENT = 'No hay al menos un destinatario elegido como firmante',
    DS_ERROR_INVALID_ORDER_RECIPIENTS = 'El orden de los firmantes debe de ser consecutivo y comenzar en 1',
    DS_ERROR_INVALID_ORDER_SIGN_RECIPIENTS = 'El último destinatario no puede ser un revisor',
    ERROR_DS_DOCUMENT_WITHOUT_PROVIDER = 'No se ha seleccionado un proveedor válido para la firma electrónica',
    DS_ERROR_NOT_COMPLETE_REMINDER = 'La configuración para los recordatorios del documento no está completa',
    ERROR_DS_DOCUMENT_WITHOUT_RECIPIENTS = 'El documento no tiene destinatarios',
    DS_ERROR_INCOMPLETE_ENVELOPE = "No ha concluido de preparar el sobre para la solicitud de firmas",
    DS_ERROR_NUM_MAX_REMINDERS = "El número de recordatorios no pueden exceder la vigencia del documento",
    DS_ERROR_REMINDERS_INCOMPLETE = "Faltan datos para configurar los recordatorios",
    DS_ERROR_REMINDERS_NOT_EXPIRATION = "Para programar recordatorios debe indicar la vigencia del documento",
    DS_INFO_CLOSE_WINDOWS_DOCUSIGN = "El proceso de posición de firma aún sigue abierta,\n Si ya finalizó presione en aceptar o cierre la ventana de DocuSign",//Proceso de firmas sin terminar\n Presione aceptar o cierre la ventana DocuSign
    DS_INFO_CLOSE_WINDOWS_DOCUSIGN_SEGUNDA="Proceso de firmas sin terminar, presione aceptar o cierre la pestaña de DocuSign",
    DS_INFO_DOCUMENT_DOCUSIGN_IN_PROCESS = "Este folio ya tiene una solicitud de firma digital para DocuSign en proceso",
    DS_INFO_NOT_CONFIGURATIONS = "No se han establecido configuraciones para este documento",


}

